<?php echo $this->doctype(); ?> 

<html>
  
<!-- HEAD
================================================================================================================ -->
<head>
    
<meta charset="utf-8" />
<title><?php echo $this->titre; ?></title>

<link rel="stylesheet" href="<?php echo $this->baseUrl('/public/css/bootstrap.min.php'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/public/css/sheet.css'); ?>">
    
</head>

<body>

<div class="contenu">
<div class="container error">


  <h1 class="text-danger">Erreur 404</h1>
  
  <p><?php //echo $this->message; ?></p>

</div>

</div>
</body>

</html>
  