<div class="four">
  <div class="jumbotron contact">
  <h3>Laissez nous un message</h3>
  <p>

    <form action="">
      
      <div class="row">
        <div class="col-md-8">

          
          <div class="form-group">
              <p class="lead">Votre nom :</p>
              <div class="controls">
                <input type="text" class="form-control" name="nom" placeholder="votre nom">
              </div>
          </div>
          <div class="form-group">
              <p class="lead">Votre email :</p>
              <div class="controls">
                <input type="text" class="form-control" name="email" placeholder="votre email">
              </div>
          </div>

          <div class="form-group">
          <p class="lead">Votre message :</p>
          <div class="controls">
            <textarea class="form-control" rows="10" name="message" placeholder="votre message"></textarea>
          </div>
      </div>
        </div>
        <div class="col-md-4">
          <blockquote>
            <p>contact@kavarilabel.com</p>
            <p>+243810936465</p>
            <p>124B, Immeuble Soki 1er Etage, Boulevard du 30 Juin, Kinshasa-Gombe.</p>
            <p><br>
            <a href="" class="soc">
              <img src="<?php echo $this->baseUrl('/public/images/ff.png'); ?>" alt="facebook"> facebook
            </a> 
            <br><br>
            <a href="" class="soc">
              <img src="<?php echo $this->baseUrl('/public/images/tw.png'); ?>" alt="facebook"> twitter
            </a>

          </blockquote>
        </div>
      </div>
      
      
      <div class="form-group">
          <div class="controls">
            <input type="submit" class="btn btn-primary btn-sm" value="envoyer">
          </div>
      </div>

    </form>

  </p>
</div>

</div>
