

<div class="contenu">
<div class="container">

<div class="row">
	<div class="col-md-12">
		<div class="jumbotron">
  			<h3>NOS ARTISTES</h3><br>
			
			<div class="row">

				<?php foreach ($this->artistes as $value): ?>
					<div class="col-md-6">
						
						<h5>
							<a href="
							<?php 
							echo $this->url(array('id'=>$value->getId(),'nom'=>urlencode($value->getNoms())),'viewartiste',true); ?>">
								<?php echo ucfirst($value->getNoms()); ?>
							</a></h5>
						
					</div>
				<?php endforeach ?>
				
			</div>

		</div>
	</div>
</div>

</div>
</div>
