
<!-- LAYOUT MODULE ADMIN 
================================================================================================================ -->
<?php echo $this->doctype(); ?> 

<html>
    
<!-- HEAD
================================================================================================================ -->
<head>
    
<meta charset="utf-8" />
<title>kavarilabel</title>
<link rel="stylesheet" href="<?php echo $this->baseUrl('/public/css/bootstrap.min.php'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/public/css/sheet.css'); ?>">
<link rel="SHORTCUT ICON"  href="<?php echo $this->baseUrl("/public/images/fav.png"); ?>">

</head>

<body>

<ul class="cb-slideshow">
    <li><span>Image 01</span></li>
    <li><span>Image 02</span></li>
    <li><span>Image 03</span></li>
    <li><span>Image 04</span></li>
    <li><span>Image 05</span></li>
    <li><span>Image 06</span></li>
</ul>

<div class="bb">

<?php echo $this->partial('menu.phtml',array('hin'=>$this->hin)); ?>

<?php echo $this->layout()->content; ?>


<div class="footer">
    <div class="container">
        <p> <small> © copyright kavarilabel.com built by <a href="http://www.gerrybeia.com">schieben</a>. contact@kavarilabel.com - +243810936465
</small> </p>
    </div>
</div>

</div>


<script src="<?php echo $this->baseUrl('/public/js/jquery.php'); ?>"></script>
<script src="<?php echo $this->baseUrl('/public/js/bootstrap.min.php'); ?>"></script>
<script src="<?php echo $this->baseUrl('/public/js/transit.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/public/js/modernizr.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/public/js/main.js'); ?>"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52671715-1', 'auto');
  ga('send', 'pageview');

</script>
</body>

</html>